language: crystal

after_success:
- scripts/generate-docs.sh
- curl https://raw.githubusercontent.com/straight-shoota/autodeploy-docs/master/autodeploy-docs.sh | bash

env:
  global:
    GIT_COMMITTER_NAME: travis-ci
    GIT_COMMITTER_EMAIL: travis@travis-ci.org
