language: crystal

env:
  global:
    GIT_COMMITTER_NAME: travis-ci
    GIT_COMMITTER_EMAIL: travis@travis-ci.org

addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats

script:
- make test
- crystal tool format --check src spec
- make integration-test
