language: crystal

env:
  global:
    GIT_COMMITTER_NAME: travis-ci
    GIT_COMMITTER_EMAIL: travis@travis-ci.org

addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats

script:
- make test
- crystal tool format --check src spec
- make integration-test
- "if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRACH -eq "master" ] && [ $TRAVIS_TEST_RESULT -eq 0 ]; then make clean-docs deploy-docs; fi"
